<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Narcotic;
use App\Narcotic_unit;
use App\NdpsCourtDetail;
use App\Unit;
use App\Agency_detail;
use App\CertifyingCourtDetail;
use App\District;
use App\Seizure;
use App\Storage_detail;
use App\Ps_detail;
use App\User;
use Carbon\Carbon;
use DB;
use Auth;

require_once base_path().'/vendor/autoload.php';


class PDFController extends Controller
{
    // Display the PDF For Monthly Report
    public function generate_monthly_report(Request $request){
        
        $user_type = Auth::user()->user_type;
        $case_no_string = $request->input('case_no_string');
        $month = $request->input('month');
        
        $report_header = '<h3 align="center">Report regarding Seizure / Disposal of Narcotic Drugs for the month of '.$month.'</h3>
                          <h3 align"center"> Court / PS / Agency : '.Auth::user()->user_name.'</h3>
                        ';

        $mpdf = new \Mpdf\Mpdf(['orientation' => 'L']);
        $content = $this->generate_pdf($report_header,$case_no_string);
        $mpdf->SetHTMLFooter('Report Generated by the DDMS - Calcutta High Court on '.Carbon::now());
        
        $mpdf->WriteHTML($content);

        if (!is_dir(base_path().'/public/temp_report_files')) 
        {
            mkdir(base_path().'/public/temp_report_files', 0777, true);       
        }
        
        if(file_exists(base_path()."/public/temp_report_files/".Auth::user()->user_id."_ddms_seizures_disposal_report.pdf"))
        {
            unlink(base_path()."/public/temp_report_files/".Auth::user()->user_id."_ddms_seizures_disposal_report.pdf");
        }
        
        $mpdf->Output(base_path()."/public/temp_report_files/".Auth::user()->user_id."_ddms_seizures_disposal_report.pdf");
        $mpdf->close();

        return asset("temp_report_files/".Auth::user()->user_id."_ddms_seizures_disposal_report.pdf");

    }



    // Display the PDF For Search Report
    public function generate_search_report(Request $request){
        
        $user_type = Auth::user()->user_type;
        $case_no_string = $request->input('case_no_string');
        
        $report_header = '<h3 align="center">Report regarding Seizure / Disposal of Narcotic Drugs</h3>
                          <h3 align"center"> Court / PS / Agency : '.Auth::user()->user_name.'</h3>
                        ';

        $mpdf = new \Mpdf\Mpdf(['orientation' => 'L']);
        $content = $this->generate_pdf($report_header,$case_no_string);
        $mpdf->SetHTMLFooter('Report Generated by the DDMS - Calcutta High Court on '.Carbon::now());
        
        $mpdf->WriteHTML($content);

        if (!is_dir(base_path().'/public/temp_report_files')) 
        {
            mkdir(base_path().'/public/temp_report_files', 0777, true);       
        }
        
        if(file_exists(base_path()."/public/temp_report_files/".Auth::user()->user_id."_ddms_seizures_disposal_report.pdf"))
        {
            unlink(base_path()."/public/temp_report_files/".Auth::user()->user_id."_ddms_seizures_disposal_report.pdf");
        }
        
        $mpdf->Output(base_path()."/public/temp_report_files/".Auth::user()->user_id."_ddms_seizures_disposal_report.pdf");
        $mpdf->close();

        return asset("temp_report_files/".Auth::user()->user_id."_ddms_seizures_disposal_report.pdf");


    }


    // Compiling the PDF
    function generate_pdf($report_header,$case_no_string){        
        $report_body = $report_header;
        $report_body = $report_body.
        '<table width="100%" style="border: 1px solid #ddd;">
            <thead>
            <tr>
                <th rowspan="2" style="border-collapse:collapse; border-right: 1px solid #ddd;">Nature of Narcotic Drug <br> / Controlled Substance</th>
                <th rowspan="2" style="border-collapse:collapse; border-right: 1px solid #ddd;">Quantity of <br>Seized Contraband</th>
                <th rowspan="2" style="border-collapse:collapse; border-right: 1px solid #ddd;">Date of Seizure</th>
                <th rowspan="2" style="border-collapse:collapse; border-right: 1px solid #ddd;">Disposal Date<br>if any, Quantity</th>
                <th rowspan="2" style="border-collapse:collapse; border-right: 1px solid #ddd;">If not disposed,<br>place of storage</th>
                <th rowspan="2" style="border-collapse:collapse; border-right: 1px solid #ddd;">Case Details</th>
                <th colspan="2" style="border-collapse:collapse; border-bottom: 1px solid #ddd;">Applied for certification</th>
            </tr>
            <tr>
                <th style="border-collapse:collapse; border-right: 1px solid #ddd;">Where</th>
                <th style="border-collapse:collapse;">Date of<br>certification</th>
            </tr>
            </thead>
            <tbody>';

        for($i=0;$i<sizeof($case_no_string);$i++){
            $case_details = $this->get_case_details($case_no_string[$i]);

            foreach ($case_details as $case) {
                $report_body =$report_body.'<tr>
                                    <td style="border-collapse:collapse; border-right: 1px solid #ddd;border-top: 1px solid #ddd;">'.$case['drug_name'].'</td>
                                    <td style="border-collapse:collapse; border-right: 1px solid #ddd;border-top: 1px solid #ddd;">'.$case['quantity_of_drug'].' '.$case['seizure_unit'].'</td>
                                    <td style="border-collapse:collapse; border-right: 1px solid #ddd;border-top: 1px solid #ddd;">'.$case['date_of_seizure'].'</td>
                                    <td style="border-collapse:collapse; border-right: 1px solid #ddd;border-top: 1px solid #ddd;">'.$case['date_of_disposal'].'<br>'.$case['disposal_quantity'].' '.$case['disposal_unit'].'</td>
                                    <td style="border-collapse:collapse; border-right: 1px solid #ddd;border-top: 1px solid #ddd;">'.$case['storage_name'].'</td>
                                    <td style="border-collapse:collapse; border-right: 1px solid #ddd;border-top: 1px solid #ddd;">Case No. '.$case_no_string[$i].'<br>'.$case['remarks'].'</td>
                                    <td style="border-collapse:collapse; border-right: 1px solid #ddd;border-top: 1px solid #ddd;">'.$case['court_name'].' ,<br>'.$case['ndps_court_name'].'</td>
                                    <td style="border-collapse:collapse;border-top: 1px solid #ddd;">'.$case['date_of_certification'].'</td>
                                </tr>
                            ';
            }
        }

        $report_body.='</tbody></table>';

        return $report_body;
    }


    // Gathering Case Details
    function get_case_details($case_no_string){        
        $case_details = Seizure::leftjoin('ps_details','seizures.ps_id','=','ps_details.ps_id')
                                ->leftjoin('agency_details','seizures.agency_id','=','agency_details.agency_id')
                                ->join('narcotics','seizures.drug_id','=','narcotics.drug_id')
                                ->join('units AS u1','seizures.seizure_quantity_weighing_unit_id','=','u1.unit_id')
                                ->leftjoin('units AS u2','seizures.sample_quantity_weighing_unit_id','=','u2.unit_id')
                                ->leftjoin('units AS u3','seizures.disposal_quantity_weighing_unit_id','=','u3.unit_id')
                                ->join('storage_details','seizures.storage_location_id','=','storage_details.storage_id')
                                ->join('certifying_court_details','seizures.certification_court_id','=','certifying_court_details.court_id')
                                ->join('ndps_court_details','seizures.ndps_court_id','=','ndps_court_details.ndps_court_id')
                                ->where('case_no_string', 'ilike', $case_no_string)  
                                ->select('drug_name','quantity_of_drug','u1.unit_name AS seizure_unit','date_of_seizure',
                                'date_of_disposal','disposal_quantity','disposal_flag','u3.unit_name AS disposal_unit',
                                'storage_name','ndps_court_name','court_name','date_of_certification','certification_flag','quantity_of_sample',
                                'u2.unit_name AS sample_unit','remarks','magistrate_remarks')
                                ->get();

        foreach($case_details as $case){
            $case['date_of_seizure'] = Carbon::parse($case['date_of_seizure'])->format('d-m-Y');
            
            if($case['certification_flag']=='Y'){                    
                $case['date_of_certification'] = Carbon::parse($case['date_of_certification'])->format('d-m-Y');
            }
            else{
                $case['date_of_certification'] = 'PENDING';
            }
            
            if($case['disposal_flag']=='Y'){                    
                $case['date_of_disposal'] = Carbon::parse($case['date_of_disposal'])->format('d-m-Y');
                $case['storage_name'] = 'NA';
            }
            else{
                $case['date_of_disposal'] = 'PENDING';
                $case['disposal_quantity'] = '';
            }

        }

        return $case_details;                                
        
    }
}
